# Generated by Django 6.0.4 on 2026-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('leida', 'Leída'), ('contactada', 'Contactada'), ('ganada', 'Ganada'), ('perdida', 'Perdida'), ('spam', 'Spam')], db_index=True, default='nueva', max_length=20)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas privadas (no visibles para el cliente).')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
